#!/bin/sh /etc/rc.common
# procd service: run the router textfile metric shims every N seconds.
# (BusyBox cron is limited to 60s; these need finer cadence.)

START=95
USE_PROCD=1

start_service() {
    procd_open_instance qosmate
    procd_set_param command /usr/bin/metrics-loop 30 /usr/bin/qosmate-prom
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

    procd_open_instance nlbwmon
    procd_set_param command /usr/bin/metrics-loop 5 /usr/bin/nlbwmon-prom
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
